# image will be published to ghcr.io/<user>/<name>
name: xerodora
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: script
    scripts:
      - custom.sh

  - type: rpm-ostree
    repos:
       # - https://repo.vivaldi.com/archive/vivaldi.repo
    install:
       - bat
       - fastfetch
       - eza
       - wget
       - git
       - dialog
       - yaml-cpp
       - gtk-update-icon-cache
       - piper
       - solaar
       - inxi
       - dnf-plugins-core
       - git-extras
       - fira-code-fonts
       - alerque-libertinus-fonts
       - source-foundry-hack-fonts
       - jetbrains-mono-fonts
       - kvantum
       - gtk-murrine-engine
       - gtk2-engines
       - gnome-themes-extra
       - xmlstarlet
       - unzip
       - jq
       - google-noto-emoji-color-fonts
       - meld
       - tree
       - btop
       - unrar
       - p7zip
       - hwinfo
       - nodejs
       - hddtemp
       - gnome-disk-utility
       - dconf-editor
       - yad
       - hardinfo2
       - timeshift
       - wine
       - wine-mono
       - wineglass
       - winetricks
       - mpv
       - kdenlive
       - libreoffice
       - hugo
       - hw-probe
       - bash-color-prompt
       - gcc
       - glow
       - gum
       - ifuse
       - input-leap
       - input-remapper
       - libxcrypt-compat
       - lm_sensors
       - make
       - nerd-fonts
       - pulseaudio-utils
       - python3-pip
       - samba
       - samba-client
       - samba-common
       - samba-libs
       - samba-tools
       - samba-usershares
       - samba-winbind
       - samba-common-libs
       - samba-common-tools
       - usbmuxd
       - zsh
       - libadwaita-qt5
       - libadwaita-qt6
       - kde-runtime-docs
       - kdenetwork-filesharing
       - kdeplasma-addons
       - plasma-wallpapers-dynamic
       - iotop
       - ImageMagick
       - dolphin-plugins
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - com.vivaldi.Vivaldi
         - com.makemkv.MakeMKV
         - de.haeckerfelix.Shortwave
         - com.usebottles.bottles
         - org.filezillaproject.Filezilla
         - com.github.KRTirtho.Spotube
         - dev.vencord.Vesktop
         - org.ferdium.Ferdium
         - com.spotify.Client
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

